[package]
name = "h3x"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
bon = "3"
dashmap = "6"
either = "1"
futures = "0.3"
http = "1"
http-body = "1"
http-body-util = "0.1"
httlib-huffman = "0.3"
pin-project-lite = "0.2"
snafu = "0.8"
tokio = "1"
tokio-util = { version = "0.7", features = ["codec", "io"] }
tracing = "0.1"
matchit = "0.9"

gm-quic = { path = "../gm-quic/gm-quic" }

[dev-dependencies]
tracing-subscriber = "0.3"
axum = "0.8"
rustls = { version = "0.23", default-features = false, features = [
    "ring",
    "logging",
] }
tokio = { version = "1", features = ["macros", "test-util", "io-util"] }
tower = "0.5"
