[package]
name = "h3x"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
bytes = "1"
bon = "3"
either = "1"
futures = "0.3"
http = "1"
httlib-huffman = { path = "../httlib-rs/huffman" }
nom = "8"
nom-bufreader = "0.2"
ouroboros = "0.18"
pin-project-lite = "0.2"
snafu = "0.8"
tokio = "1"
tokio-util = { version = "0.7", features = ["codec", "io"] }


gm-quic = { path = "../gm-quic/gm-quic" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "test-util", "io-util"] }
